# Generated by Django 2.0.1 on 2018-02-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0003_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followedBy', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='followedBy', to='user_app.MyUser')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='user_app.MyUser')),
            ],
        ),
    ]
