# Generated by Django 2.0.1 on 2018-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20180114_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbrick',
            name='sport_name',
            field=models.CharField(default='default', max_length=40),
            preserve_default=False,
        ),
    ]
