# Generated by Django 2.0.1 on 2018-01-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('image_name', models.CharField(max_length=50)),
                ('user_brick', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wall.UserBrick')),
            ],
        ),
    ]
