# Generated by Django 2.0.1 on 2018-02-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
